export const PROJECTS = [
    {
        title: "Livraria Social",
        image: "/assets/imgs/img_livraria_social.png",
        role: "Full Stack",
        date: "ago 2023 - nov 2023",
        description: "Sistema web para resenhas literárias e descoberta de livros, integrado à API do Google Books, com gerenciamento de listas de leitura e recomendações personalizadas.",
        stacks: ["Django", "Bootstrap", "JavaScript", "PostgreSQL", "Figma", "Docker", "Jira"],
        access_link: "https://livraria-social.onrender.com/",
        github_link: "https://github.com/matheusvictor0/Livraria_Social",
    },
    {
        title: "Diário de Viagens",
        image: "/assets/imgs/img_diario_de_viagens.jpg",
        role: "UI Designer",
        date: "mar 2024 - mai 2024",
        description: "Protótipos de baixa e média fidelidade para uma interface mobile dedicada ao registro de viagens, compartilhamento de experiências, recomendações de locais e definição de metas para viagens futuras.",
        stacks: ["Figma", "Jira"],
        access_link: "https://www.figma.com/design/3G7G7oGcwv7dfGmPoqVh0n/Projeto-Diario-de-Viagens?node-id=0-1&t=nBWZMqYgUSKMASi0-1",
        // github_link: "",
    },
    {
        title: "Redesign VLibras",
        image: "/assets/imgs/redesign-vlibras.png",
        role: "UX/UI Designer",
        date: "mar 2024 - mai 2024",
        description: "Pesquisa e análise de apps de tradução Português–Libras com redesign do app VLibras baseado nas heurísticas de Nielsen para melhorar usabilidade e experiência do usuário.",
        stacks: ["Figma", "UX/UI"],
        access_link: "https://www.figma.com/design/HqIRYzz46XMUV3M7MxSg86/Redesign-VLibras---TCC?node-id=0-1&t=yQMWkvKIZEVaTqB7-1",
        // github_link: "",
    },
    {
        title: "PouPay",
        image: "/assets/imgs/img_poupay.jpg",
        role: "UX/UI Designer",
        date: "ago 2023 - nov 2023",
        description: "Contribuição no protótipo e layout de um aplicativo de gerenciamento financeiro pessoal. O app visa organizar e controlar finanças de forma intuitiva e amigável para os usuários.",
        stacks: ["Figma", "Kotlin", "Scrum"],
        access_link: "https://www.figma.com/design/JKECWOJgm3NV9ixWX35S26/app-PouPay?node-id=0-1&t=kXoxKyM7apWJnVQQ-1",
        github_link: "https://github.com/poupayuepb/PouPay",
    },
    {
        title: "EventFinder",
        image: "/assets/imgs/img_eventfinder.png",
        role: "Full Stack",
        date: "abr 2024 - jul 2024",
        description: "Plataforma web para busca e gerenciamento de eventos, que permite aos usuários encontrar eventos por categoria ou localização.",
        stacks: ["ReactJS", "styled-components", "Node.js", "Express.js", "MongoDB"],
        access_link: "https://eventfinder-web.netlify.app/",
        github_link: "https://github.com/vitoriaalbuqrq/EventFinder",
    },
    {
        title: "Project Costs",
        image: "/assets/imgs/img_projectcosts.png",
        role: "Full Stack",
        date: "ago 2024",
        description: "Sistema de gerenciamento de projetos com autenticação de usuários, que permite organizar projetos por categorias, calcular custos e monitorar o orçamento de forma simplificada.",
        stacks: ["Spring Boot", "Angular", "SCSS", "JWT", "Docker", "PostgreSQL", "Deploy"],
        access_link: "https://project-costs-five.vercel.app/",
        github_link: "https://github.com/vitoriaalbuqrq/project-costs-backend",
    },
    {
        title: "VotEasy",
        image: "/assets/imgs/img-voteasy.png",
        role: "Full Stack",
        date: "mar 2025 - ago 2025",
        description: "Aplicação web que permite criar, gerenciar e participar de votações online de forma prática, garantindo transparência, imutabilidade e confiabilidade com o uso da blockchain.",
        stacks: ["Next.js", "Tailwind CSS", "Solidity", "Express.js", "MongoDB", "Hardhat", "Metamask"],
        github_link: "https://github.com/vitoriaalbuqrq/VotEasy",
    },
    /*{
        title: "ToDoList",
        image: "/assets/imgs/todolist.png",
        date: "fevereiro 2024",
        description: "ToDoList é uma aplicação de lista de tarefas que permite aos usuários criar, gerenciar e marcar tarefas concluídas. Utiliza React para o frontend e Node.js com Express para o backend, integrando MongoDB.",
        stacks: ["Node.js", "Express.js", "ReactJS", "Css", "MongoDB"],
        github_link: "https://github.com/vitoriaalbuqrq/ToDo-List",
    },
    {
        title: "Conversor de bases numéricas",
        image: "/assets/imgs/conversor_bases.png",
        date: "agosto 2024",
        description: "Conversor de bases numéricas desenvolvido em JavaScript e CSS, capaz de converter números das bases 2 até 16. Criado como parte dos estudos na disciplina de Cálculo Numérico para facilitar aprendizado e aplicação prática.",
        stacks: ["JavaScript", "Css", "HTML"],
        access_link: "https://vitoriaalbuqrq.github.io/conversor-de-bases/",
        github_link: "https://github.com/vitoriaalbuqrq/conversor-de-bases",
    },*/
]