export const PROJECTS = [
    {
        title: "Livraria Social",
        image: "/assets/imgs/img_livraria_social.png",
        date: "agosto 2023 - novembro 2023",
        description: "Sistema web para resenhas literárias e descoberta de livros, com gerenciamento de listas de leitura e recomendações personalizadas. Integra a API do Google Books e utiliza Scrum e Jira para gestão ágil.",
        stacks: ["Django", "HTML5", "CSS3", "Bootstrap", "JavaScript", "PostgreSQL", "Figma", "Docker", "Jira"],
        access_link: "https://livraria-social.onrender.com/",
        github_link: "https://github.com/matheusvictor0/Livraria_Social",
    },
    {
        title: "Diário de Viagens",
        image: "/assets/imgs/img_diario_de_viagens.jpg",
        date: "março 2024 - maio 2024",
        description: "Protótipos de baixa e média fidelidade para uma interface mobile dedicada ao registro de viagens, compartilhamento de experiências, recomendações de locais e definição de metas para viagens futuras.",
        stacks: ["Figma", "Jira"],
        access_link: "https://www.figma.com/design/3G7G7oGcwv7dfGmPoqVh0n/Projeto-Diario-de-Viagens?node-id=0-1&t=nBWZMqYgUSKMASi0-1",
        // github_link: "",
    },
    {
        title: "EventFinder",
        image: "/assets/imgs/img_eventfinder.png",
        date: "abril 2024 - julho 2024",
        description: "Plataforma web para busca e gerenciamento de eventos, com CRUD completo. Backend em Node.js/Express integrado ao MongoDB, frontend em React com styled-components. Deploy no Netlify (frontend) e Render (backend).",
        stacks: ["ReactJS", "styled-components", "Node.js", "Express.js", "MongoDB"],
        access_link: "https://eventfinder-web.netlify.app/",
        github_link: "https://github.com/vitoriaalbuqrq/EventFinder",
    },
    {
        title: "PouPay",
        image: "/assets/imgs/img_poupay.jpg",
        date: "agosto 2023 - novembro 2023",
        description: "Participei do desenvolvimento de um aplicativo de gerenciamento financeiro pessoal, contribuindo na criação do protótipo e layout da interface. O app visa organizar e controlar finanças de forma intuitiva e amigável para os usuários.",
        stacks: ["Figma", "Kotlin", "Scrum"],
        access_link: "https://www.figma.com/design/JKECWOJgm3NV9ixWX35S26/app-PouPay?node-id=0-1&t=kXoxKyM7apWJnVQQ-1",
        github_link: "https://github.com/poupayuepb/PouPay",
    },
    {
        title: "Gerenciamento de restaurantes universitários",
        image: "/assets/imgs/restaurante_uni.png",
        date: "maio 2023",
        description: "Sistema web de gerenciamento simples para restaurantes universitários, alunos e endereços, com operações CRUD. Implementa uma API utilizando Spring Boot no backend e frontend desenvolvido em React com Material UI.",
        stacks: ["SpringBoot", "ReactJS", "Material UI", "Postman"],
        github_link: "https://github.com/vitoriaalbuqrq/projeto-restaurante-universitario-backend",
    },
    {
        title: "ToDoList",
        image: "/assets/imgs/todolist.png",
        date: "fevereiro 2024",
        description: "ToDoList é uma aplicação de lista de tarefas que permite aos usuários criar, gerenciar e marcar tarefas concluídas. Utiliza React para o frontend e Node.js com Express para o backend, integrando MongoDB.",
        stacks: ["Node.js", "Express.js", "ReactJS", "Css", "MongoDB"],
        github_link: "https://github.com/vitoriaalbuqrq/ToDo-List",
    },
    {
        title: "Conversor de bases numéricas",
        image: "/assets/imgs/conversor_bases.png",
        date: "agosto 2024",
        description: "Conversor de bases numéricas desenvolvido em JavaScript e CSS, capaz de converter números das bases 2 até 16. Criado como parte dos estudos na disciplina de Cálculo Numérico para facilitar aprendizado e aplicação prática.",
        stacks: ["JavaScript", "Css", "HTML"],
        access_link: "https://vitoriaalbuqrq.github.io/conversor-de-bases/",
        github_link: "https://github.com/vitoriaalbuqrq/conversor-de-bases",
    },
]